/* WC2026 trip seed data — with coordinates, hotel addresses & maps queries */
(function () {
  const STOPS = [
    {
      id: "vancouver", n: 1, name: "Vancouver", region: "British Columbia", country: "CA",
      dates: "12–14 Jun", arrive: "2026-06-12", depart: "2026-06-14",
      hotel: "OPUS Vancouver", hotel_address: "322 Davie St, Vancouver, BC V6B 5Z6",
      hotel_note: "Yaletown. Great location, no need to relocate.",
      hotel_maps: "OPUS Vancouver, 322 Davie St, Vancouver BC",
      tagline: "Yaletown base · Group D opener",
      coords: { lat: 49.2827, lng: -123.1207 },
      map: { x: 38, y: 6 },
    },
    {
      id: "seattle1", n: 2, name: "Seattle", region: "Washington · Round 1", country: "US",
      dates: "14–16 Jun", arrive: "2026-06-14", depart: "2026-06-16",
      hotel: "Fairfield by Marriott Seattle Center",
      hotel_address: "200 Taylor Ave N, Seattle, WA 98109",
      hotel_note: "Central. Fan-zone day right outside the door.",
      hotel_maps: "Fairfield by Marriott Seattle Downtown, Taylor Ave N, Seattle WA",
      tagline: "Fan-zone & Seattle Center",
      coords: { lat: 47.6205, lng: -122.3493 },
      map: { x: 36, y: 17 },
    },
    {
      id: "olympic", n: 3, name: "Port Angeles", region: "Olympic National Park", country: "US",
      dates: "16–18 Jun", arrive: "2026-06-16", depart: "2026-06-18",
      hotel: "Olympic Lodge by Ayres",
      hotel_address: "140 Del Guzzi Dr, Port Angeles, WA 98362",
      hotel_note: "Wilderness reset. Pick up rental car. ~2.5 hr from Seattle.",
      hotel_maps: "Olympic Lodge by Ayres, 140 Del Guzzi Dr, Port Angeles WA",
      tagline: "Rainforest, ridges & marmots",
      coords: { lat: 48.1181, lng: -123.4307 },
      map: { x: 20, y: 22 },
    },
    {
      id: "seattle2", n: 4, name: "Seattle", region: "Washington · Round 2", country: "US",
      dates: "18–20 Jun", arrive: "2026-06-18", depart: "2026-06-20",
      hotel: "Four Points by Sheraton Seattle Airport South",
      hotel_address: "2688 S 188th St, SeaTac, WA 98188",
      hotel_note: "Airport-strip hotel. Don't try to eat or drink near it — Uber out.",
      hotel_maps: "Four Points by Sheraton Seattle Airport South, SeaTac WA",
      tagline: "USA vs Australia · loaded sports stretch",
      coords: { lat: 47.4494, lng: -122.3013 },
      map: { x: 38, y: 30 },
    },
    {
      id: "portland", n: 5, name: "Portland", region: "Oregon", country: "US",
      dates: "20–21 Jun", arrive: "2026-06-20", depart: "2026-06-21",
      hotel: "Embassy Suites by Hilton Portland Downtown",
      hotel_address: "319 SW Pine St, Portland, OR 97204",
      hotel_note: "Central, fine. One night only — arrive ~lunch Sat 20 (5 hr drive).",
      hotel_maps: "Embassy Suites Portland Downtown, 319 SW Pine St, Portland OR",
      tagline: "Pickles, Powell's, hazy IPA",
      coords: { lat: 45.5231, lng: -122.6765 },
      map: { x: 34, y: 45 },
    },
    {
      id: "craterlake", n: 6, name: "Crater Lake", region: "Oregon", country: "US",
      dates: "21–23 Jun", arrive: "2026-06-21", depart: "2026-06-23",
      hotel: "Crater Lake Lodge",
      hotel_address: "565 Rim Dr, Crater Lake, OR 97604",
      hotel_note: "Remote and iconic. ~7,100 ft — pace yourself, expect snow on trails.",
      hotel_maps: "Crater Lake Lodge, Rim Village, Crater Lake OR",
      tagline: "The deepest blue in America",
      coords: { lat: 42.9446, lng: -122.1090 },
      map: { x: 42, y: 58 },
    },
    {
      id: "napa", n: 7, name: "Napa Valley", region: "California · Yountville", country: "US",
      dates: "23–25 Jun", arrive: "2026-06-23", depart: "2026-06-25",
      hotel: "Napa Valley Lodge",
      hotel_address: "2230 Madison St, Yountville, CA 94599",
      hotel_note: "Great spot. Stay put. Easy wine-country day on the 24th.",
      hotel_maps: "Napa Valley Lodge, 2230 Madison St, Yountville CA",
      tagline: "Decompress · vines & long lunches",
      coords: { lat: 38.4027, lng: -122.3616 },
      map: { x: 36, y: 76 },
    },
    {
      id: "southbay", n: 8, name: "San Jose / SF", region: "South Bay", country: "US",
      dates: "25–26 Jun", arrive: "2026-06-25", depart: "2026-06-26",
      hotel: "Country Inn & Suites San Jose Airport",
      hotel_address: "1350 N 1st St, San Jose, CA 95112",
      hotel_note: "Bland North San Jose. Uber out for everything. Will flies 10pm on the 26th.",
      hotel_maps: "Country Inn and Suites San Jose Airport, 1350 N 1st St, San Jose CA",
      tagline: "Group D finale at Levi's",
      coords: { lat: 37.3737, lng: -121.9220 },
      map: { x: 44, y: 90 },
    },
  ];

  const MATCHES = [
    {
      id: "m-aus-tur", date: "2026-06-13", time: "21:00",
      home: "Australia", away: "Türkiye", label: "Group D · Matchday 1",
      venue: "BC Place", city: "Vancouver", stop: "vancouver", hero: true, socceroos: true,
      maps: "BC Place, 777 Pacific Blvd, Vancouver BC",
      note: "SkyTrain Stadium–Chinatown CLOSED on match days. Use Main Street–Science World. 'Last Mile' fan walk starts ~2 hrs before kickoff.",
    },
    {
      id: "m-bel-egy", date: "2026-06-15", time: "12:00",
      home: "Belgium", away: "Egypt", label: "Group · Fan-zone day",
      venue: "Lumen Field", city: "Seattle", stop: "seattle1", hero: false, socceroos: false,
      maps: "Lumen Field, 800 Occidental Ave S, Seattle WA",
      note: "Official FIFA fan celebration at Seattle Center — basically next to your hotel.",
    },
    {
      id: "m-usa-aus", date: "2026-06-19", time: "12:00",
      home: "USA", away: "Australia", label: "Group D · Matchday 2 · YOUR USA TICKET",
      venue: "Lumen Field", city: "Seattle", stop: "seattle2", hero: true, socceroos: true,
      maps: "Lumen Field, 800 Occidental Ave S, Seattle WA",
      note: "Bonus: Mariners vs Boston 7:10pm same night next door. Noon match + evening MLB is very doable.",
    },
    {
      id: "m-par-aus", date: "2026-06-25", time: "19:00",
      home: "Paraguay", away: "Australia", label: "Group D · Matchday 3 · The Finale",
      venue: "Levi's Stadium", city: "Santa Clara", stop: "southbay", hero: true, socceroos: true,
      maps: "Levi's Stadium, 4900 Marie P DeBartolo Way, Santa Clara CA",
      note: "~15 min from hotel — leave a big buffer for traffic.",
    },
  ];

  const I = (stop, title, cat, desc, opts = {}) => ({
    id: `${stop}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40)}`,
    stop, title, cat, desc,
    pinned: !!opts.pinned, must: !!opts.must, by: opts.by || "seed",
    maps: opts.maps || `${title}, ${STOPS.find(s=>s.id===stop)?.name}`,
    ...opts,
  });

  const IDEAS = [
    // ===================== VANCOUVER =====================
    I("vancouver", "FIFA Fan Festival at the PNE", "sport", "Free. Giant screens. All tournament long. Hastings Park.", { maps: "PNE Hastings Park, Vancouver BC" }),
    I("vancouver", "Vancouver Canadians (High-A)", "baseball", "Home series at The Nat through ~June 14. Fri 12 evening = classic small-park night.", { date: "2026-06-12", time: "evening", confirm: true, maps: "Nat Bailey Stadium, 4601 Ontario St, Vancouver BC" }),
    I("vancouver", "BC Place tour / BC Sports Hall of Fame", "sport", "Inside the stadium.", { maps: "BC Place, 777 Pacific Blvd, Vancouver BC" }),
    I("vancouver", "Kayak / SUP on False Creek", "sport", "Rentals on False Creek.", { maps: "False Creek, Vancouver BC" }),
    I("vancouver", "Gastown wander", "culture", "Cobblestone old town and the Steam Clock.", { maps: "Gastown, Vancouver BC" }),
    I("vancouver", "Chinatown & Sun Yat-Sen Garden", "garden", "First authentic full-scale classical Chinese garden outside China.", { maps: "Dr Sun Yat-Sen Classical Chinese Garden, 578 Carrall St, Vancouver BC" }),
    I("vancouver", "Granville Island Public Market", "market", "Aquabus across False Creek. Food, makers, buskers.", { pinned: true, maps: "Granville Island Public Market, Vancouver BC" }),
    I("vancouver", "Museum of Vancouver + Maritime Museum", "museum", "Vanier Park double-feature.", { maps: "Museum of Vancouver, 1100 Chestnut St, Vancouver BC" }),
    I("vancouver", "Vancouver Art Gallery", "museum", "Emily Carr, Indigenous art.", { maps: "Vancouver Art Gallery, 750 Hornby St, Vancouver BC" }),
    I("vancouver", "Capilano Suspension Bridge / Grouse Mountain", "dayout", "North Shore, ~25 min. Forest-and-views half-day.", { maps: "Capilano Suspension Bridge Park, North Vancouver BC" }),
    I("vancouver", "Bill Reid Gallery of Northwest Coast Art", "museum", "Superb Haida/Indigenous art downtown. Free first Friday afternoon.", { maps: "Bill Reid Gallery, 639 Hornby St, Vancouver BC" }),
    I("vancouver", "VanDusen Botanical Garden", "garden", "55 acres of themed gardens near Queen Elizabeth Park.", { maps: "VanDusen Botanical Garden, Vancouver BC" }),
    I("vancouver", "The Polygon Gallery (North Van)", "museum", "Striking waterfront photography gallery. Pairs with Lonsdale Quay market.", { maps: "The Polygon Gallery, 101 Carrie Cates Ct, North Vancouver BC" }),
    I("vancouver", "Stanley Park Seawall run", "run", "~10km car-free loop. Ocean + old-growth forest. The definitive Vancouver run.", { pinned: true, maps: "Stanley Park Seawall, Vancouver BC" }),
    I("vancouver", "False Creek loop run", "run", "Straight from the door. Shorter, flat.", { maps: "False Creek Seawall, Vancouver BC" }),
    I("vancouver", "Vancouver Fish Company", "food", "Pacific NW seafood — sablefish, spot prawns, oysters.", { maps: "Vancouver Fish Company, 1505 W 1st Ave, Vancouver BC" }),
    I("vancouver", "Cardero's (Coal Harbour patio)", "food", "Seafood, patio over the marina.", { maps: "Cardero's Restaurant, 1583 Coal Harbour Quay, Vancouver BC" }),
    I("vancouver", "Oshi Nori", "food", "Handroll sushi, Yaletown.", { maps: "Oshi Nori, Yaletown, Vancouver BC" }),
    I("vancouver", "Elisa", "food", "Steak. Yaletown.", { maps: "Elisa Restaurant, Vancouver BC" }),
    I("vancouver", "Dovetail", "food", "Lively modern. Yaletown.", { maps: "Dovetail Restaurant, Yaletown, Vancouver BC" }),
    I("vancouver", "Brix & Mortar", "food", "Yaletown classic.", { maps: "Brix and Mortar, 1137 Hamilton St, Vancouver BC" }),
    I("vancouver", "Richmond dim sum / night market", "food", "~25 min, by the airport. Some of the best Chinese food outside Asia.", { maps: "Richmond Night Market, Richmond BC" }),
    I("vancouver", "Tonkotsu Ramen Tsukiya", "food", "West End. Tiny, superb broth.", { maps: "Ramen Tsukiya, Vancouver BC" }),
    I("vancouver", "Menya Raizo", "food", "Ramen on Broadway.", { maps: "Menya Raizo, Vancouver BC" }),
    I("vancouver", "Oku Izakaya", "food", "Sake + sushi. Gastown.", { maps: "Oku Restaurant, Gastown, Vancouver BC" }),
    I("vancouver", "Desi Indian Lounge", "food", "Downtown. Vancouver is strong on Indian.", { maps: "Desi Indian Lounge, Vancouver BC" }),
    I("vancouver", "The Farmhouse (Main St)", "food", "Rustic Italian, Mount Pleasant strip.", { maps: "The Farmhouse, Main Street, Vancouver BC" }),
    I("vancouver", "The Watson", "bar", "Excellent cocktail bar, Main St.", { maps: "The Watson, 1019 Main St, Vancouver BC" }),
    I("vancouver", "Guilt & Co", "bar", "Live music basement, Gastown.", { maps: "Guilt and Company, 1 Alexander St, Vancouver BC" }),
    I("vancouver", "Arcana", "bar", "Theatrical cocktails, Gastown.", { maps: "Arcana Bar, Gastown, Vancouver BC" }),

    // ===================== SEATTLE ROUND 1 =====================
    I("seattle1", "Seattle Storm (WNBA)", "wnba", "Climate Pledge Arena — 5-min walk from your hotel. Check 14th/15th.", { confirm: true, maps: "Climate Pledge Arena, 334 1st Ave N, Seattle WA" }),
    I("seattle1", "Tacoma Rainiers (AAA)", "baseball", "Home Sun 14, 1:35pm vs Albuquerque (~35 min south). Only if you land early.", { date: "2026-06-14", time: "13:35", confirm: true, maps: "Cheney Stadium, 2502 S Tyler St, Tacoma WA" }),
    I("seattle1", "Pike Place Market — go early", "market", "The classic. Earlier the better.", { pinned: true, maps: "Pike Place Market, 85 Pike St, Seattle WA" }),
    I("seattle1", "Chihuly Garden and Glass", "museum", "By your hotel. Pairs with Space Needle.", { maps: "Chihuly Garden and Glass, 305 Harrison St, Seattle WA" }),
    I("seattle1", "Space Needle", "view", "By your hotel.", { maps: "Space Needle, 400 Broad St, Seattle WA" }),
    I("seattle1", "MOHAI on Lake Union", "museum", "Best city-history museum.", { maps: "MOHAI Museum of History and Industry, 860 Terry Ave N, Seattle WA" }),
    I("seattle1", "Smith Tower speakeasy bar", "bar", "Observation bar in Pioneer Square.", { maps: "Smith Tower, 506 2nd Ave, Seattle WA" }),
    I("seattle1", "Pioneer Square Underground Tour", "culture", "The buried original city. Great rainy-hour option.", { maps: "Bill Speidel's Underground Tour, 614 1st Ave, Seattle WA" }),
    I("seattle1", "Museum of Pop Culture (MoPOP)", "museum", "Hendrix/Nirvana, sci-fi & horror props, guitar tower. Right by hotel.", { maps: "MoPOP Museum of Pop Culture, 325 5th Ave N, Seattle WA" }),
    I("seattle1", "Frye Art Museum", "museum", "First Hill. Small, excellent, free. One-hour escape.", { maps: "Frye Art Museum, 704 Terry Ave, Seattle WA" }),
    I("seattle1", "Ballard Locks", "view", "Watch boats lift between sea & lake; salmon-ladder window.", { maps: "Hiram M Chittenden Locks, 3015 NW 54th St, Seattle WA" }),
    I("seattle1", "Elliott Bay Trail run", "run", "Myrtle Edwards Park from Olympic Sculpture Park. Flat waterfront — the signature Seattle run.", { pinned: true, maps: "Elliott Bay Trail, Myrtle Edwards Park, Seattle WA" }),
    I("seattle1", "Kerry Park (Queen Anne)", "view", "Skyline-postcard hill. Add to a run.", { maps: "Kerry Park, 211 W Highland Dr, Seattle WA" }),
    I("seattle1", "Taylor Shellfish (Pioneer Sq)", "food", "Oysters.", { maps: "Taylor Shellfish Oyster Bar, 410 Broadway E, Seattle WA" }),
    I("seattle1", "The Walrus and the Carpenter (Ballard)", "food", "Cult oyster bar.", { maps: "The Walrus and the Carpenter, 4743 Ballard Ave NW, Seattle WA" }),
    I("seattle1", "Local Tide (Fremont)", "food", "Crab roll.", { maps: "Local Tide, 4408 Stone Way N, Seattle WA" }),
    I("seattle1", "Kedai Makan", "food", "Malaysian, Capitol Hill.", { maps: "Kedai Makan, 1802 Bellevue Ave, Seattle WA" }),
    I("seattle1", "Terra Plata", "food", "Rooftop, Capitol Hill.", { maps: "Terra Plata, 1501 Melrose Ave, Seattle WA" }),
    I("seattle1", "Majnoon (Queen Anne)", "bar", "Near hotel, rare agave list.", { maps: "Majnoon Bar, Queen Anne, Seattle WA" }),
    I("seattle1", "Paper Fan", "bar", "Capitol Hill speakeasy.", { maps: "Paper Fan Seattle, Capitol Hill, Seattle WA" }),
    I("seattle1", "Canlis", "food", "Iconic Lake Union fine-diner. Book well ahead.", { confirm: true, maps: "Canlis Restaurant, 2576 Aurora Ave N, Seattle WA" }),
    I("seattle1", "Archipelago", "food", "Intimate Filipino tasting menu, Columbia City.", { maps: "Archipelago Restaurant, 3804 S Hudson St, Seattle WA" }),

    // ===================== OLYMPIC NP =====================
    I("olympic", "Port Angeles Lefties (WCL)", "baseball", "Home Tue 16 & Wed 17, 6:35pm vs Bellingham at Civic Field. Sunset over the Strait.", { date: "2026-06-16", time: "18:35", pinned: true, maps: "Civic Field, Port Angeles WA" }),
    I("olympic", "Hurricane Ridge", "view", "~40 min up. Alpine meadows, Olympic Mountain panoramas. Clearest morning.", { pinned: true, must: true, maps: "Hurricane Ridge Visitor Center, Olympic National Park, Port Angeles WA" }),
    I("olympic", "Lake Crescent — Marymere Falls", "park", "Easy 1.5mi.", { maps: "Marymere Falls Trail, Lake Crescent, Olympic National Park WA" }),
    I("olympic", "Mt. Storm King scramble", "park", "Steep, ropes near the top, huge payoff. From Lake Crescent.", { maps: "Storm King Mountain Trail, Lake Crescent, WA" }),
    I("olympic", "Hoh Rain Forest — Hall of Mosses", "park", "~2 hr each way. Otherworldly. Long but worthwhile.", { must: true, maps: "Hall of Mosses Trail, Hoh Rain Forest, Olympic National Park WA" }),
    I("olympic", "Sol Duc Falls", "park", "Short forest walk to a beautiful falls.", { maps: "Sol Duc Falls Trail, Olympic National Park WA" }),
    I("olympic", "Rialto / Ruby Beach", "park", "Pacific sea stacks if you swing coastward.", { maps: "Ruby Beach, Olympic National Park WA" }),
    I("olympic", "Sequim lavender farms", "dayout", "~20 min east, e.g. Purple Haze. Fields blooming in June. Lavender lemonade.", { maps: "Purple Haze Lavender Farm, Sequim WA" }),
    I("olympic", "Olympic Discovery Trail run", "run", "Paved waterfront/forest path through Port Angeles. Flat, right by the lodge.", { maps: "Olympic Discovery Trail, Port Angeles WA" }),
    I("olympic", "Dungeness crab around the harbor", "food", "Local catch.", { maps: "Port Angeles Harbor, Port Angeles WA" }),
    I("olympic", "Next Door Gastropub", "food", "Downtown dinner.", { maps: "Next Door Gastropub, 113 W 1st St, Port Angeles WA" }),
    I("olympic", "Barhop Brewing", "drink", "Local pint.", { maps: "Barhop Brewing, Port Angeles WA" }),

    // ===================== SEATTLE ROUND 2 =====================
    I("seattle2", "Mariners vs Baltimore (day game)", "baseball", "Thu 18, 1:10pm at T-Mobile Park. Slots perfectly into your open day.", { date: "2026-06-18", time: "13:10", pinned: true, maps: "T-Mobile Park, 1250 1st Ave S, Seattle WA" }),
    I("seattle2", "Mariners vs Boston — evening", "baseball", "Fri 19, 7:10pm at T-Mobile, same night as USA match. Doable noon match + evening MLB.", { date: "2026-06-19", time: "19:10", maps: "T-Mobile Park, 1250 1st Ave S, Seattle WA" }),
    I("seattle2", "Georgetown — Kuma Kitchen", "food", "Pan-Asian. Scruffy-cool neighborhood ~10 min Uber.", { maps: "Kuma Kitchen, Georgetown, Seattle WA" }),
    I("seattle2", "Georgetown — 1988 Cocktail Lounge", "bar", "Tiny, excellent.", { maps: "1988 Cocktail Lounge, Georgetown, Seattle WA" }),
    I("seattle2", "Alki Beach — Driftwood", "food", "Farm-to-table, superb.", { maps: "Driftwood Restaurant, Alki Beach, Seattle WA" }),
    I("seattle2", "Alki Beach — Otter on the Rocks", "bar", "Cocktails.", { maps: "Otter on the Rocks, Alki Beach, Seattle WA" }),
    I("seattle2", "Des Moines Creek Trail run", "run", "Paved, wooded, creek-side. Best run near the airport hotels.", { maps: "Des Moines Creek Trail, Des Moines WA" }),

    // ===================== PORTLAND =====================
    I("portland", "Portland Pickles (WCL) — Mom's Night", "baseball", "Sat 20 at Walker Stadium. Leads WCL in attendance. Most-fun, most-Portland.", { date: "2026-06-20", time: "evening", pinned: true, maps: "Walker Stadium, 4727 SE Milwaukie Ave, Portland OR" }),
    I("portland", "Portland Fire (WNBA)", "wnba", "Brand-new team's inaugural season at Moda Center. Confirm schedule.", { confirm: true, date: "2026-06-20", time: "17:30", maps: "Moda Center, 1 N Center Court St, Portland OR" }),
    I("portland", "Powell's City of Books", "culture", "A full city block.", { pinned: true, maps: "Powell's City of Books, 1005 W Burnside St, Portland OR" }),
    I("portland", "Lan Su Chinese Garden", "garden", "Downtown classical garden.", { maps: "Lan Su Chinese Garden, 239 NW Everett St, Portland OR" }),
    I("portland", "Portland Japanese Garden", "garden", "Washington Park. Often called the best outside Japan.", { must: true, maps: "Portland Japanese Garden, 611 SW Kingston Ave, Portland OR" }),
    I("portland", "International Rose Test Garden", "garden", "Free, peak bloom in June. Adjacent to Japanese Garden.", { maps: "International Rose Test Garden, 400 SW Kingston Ave, Portland OR" }),
    I("portland", "Portland Art Museum", "museum", "Recently expanded. Room devoted to Portland-raised Mark Rothko.", { maps: "Portland Art Museum, 1219 SW Park Ave, Portland OR" }),
    I("portland", "Waterfront loop run", "run", "Tom McCall → cross river → Eastbank Esplanade → back. ~4mi car-free.", { maps: "Tom McCall Waterfront Park, Portland OR" }),
    I("portland", "Cartopia food carts (Hawthorne)", "food", "Fire pits at night.", { maps: "Cartopia Food Cart Pod, 1207 SE Hawthorne Blvd, Portland OR" }),
    I("portland", "Voodoo Doughnut", "food", "Touristy but obligatory.", { maps: "Voodoo Doughnut, 22 SW 3rd Ave, Portland OR" }),
    I("portland", "Screen Door — Southern brunch", "food", "Expect a line.", { maps: "Screen Door Restaurant, 2337 E Burnside St, Portland OR" }),
    I("portland", "Farmhouse Kitchen Thai", "food", "Spectacular.", { maps: "Farmhouse Kitchen Thai Cuisine, Portland OR" }),
    I("portland", "Teardrop Lounge", "bar", "Top-tier cocktails.", { maps: "Teardrop Lounge, 1015 NW Everett St, Portland OR" }),
    I("portland", "Hat Yai", "food", "Famous Southern-Thai fried chicken + curry.", { maps: "Hat Yai, 1605 NE Killingsworth St, Portland OR" }),
    I("portland", "Salt & Straw", "food", "Cult ice cream. NW 23rd & SE Division.", { pinned: true, maps: "Salt and Straw, 838 NW 23rd Ave, Portland OR" }),

    // ===================== CRATER LAKE =====================
    I("craterlake", "Sunset drink on the Lodge terrace", "view", "Crater Lake Lodge (1915). Over the caldera. The classic.", { pinned: true, must: true, maps: "Crater Lake Lodge, 565 Rim Dr, Crater Lake OR" }),
    I("craterlake", "Rim Drive (33-mi loop)", "view", "Check how much is plowed/open in June.", { maps: "Rim Drive, Crater Lake National Park OR" }),
    I("craterlake", "Watchman Peak — sunset", "park", "Short, steep. Best sunset over Wizard Island.", { maps: "Watchman Peak Trail, Crater Lake National Park OR" }),
    I("craterlake", "Garfield Peak — from the lodge", "park", "~3.4mi. Big views.", { maps: "Garfield Peak Trail, Crater Lake National Park OR" }),
    I("craterlake", "Cleetwood Cove + boat tour", "park", "Only legal trail to the water. Boat tours if running.", { maps: "Cleetwood Cove Trail, Crater Lake National Park OR" }),
    I("craterlake", "Crater Lake Lodge Dining Room", "food", "Regional plates with the view. Book ahead.", { confirm: true, maps: "Crater Lake Lodge Dining Room, Crater Lake OR" }),
    I("craterlake", "Annie Creek (Mazama Village)", "food", "Casual alternative.", { maps: "Mazama Village, Crater Lake National Park OR" }),

    // ===================== NAPA =====================
    I("napa", "Sacramento River Cats (AAA)", "baseball", "~1 hr from Napa. Home Tue 23, 6:45pm vs Las Vegas. Temporary MLB home of the Athletics.", { date: "2026-06-23", time: "18:45", confirm: true, maps: "Sutter Health Park, 400 Ballpark Dr, Sacramento CA" }),
    I("napa", "Hot-air balloon sunrise", "dayout", "The classic Napa morning. Decompress mode.", { must: true, maps: "Napa Valley Aloft Balloons, Yountville CA" }),
    I("napa", "Napa Valley Vine Trail by bike", "sport", "Cycle between wineries. Paved.", { maps: "Napa Valley Vine Trail, Yountville CA" }),
    I("napa", "Oxbow Public Market", "market", "Walk-around lunch in downtown Napa.", { maps: "Oxbow Public Market, 610 1st St, Napa CA" }),
    I("napa", "Castello di Amorosa", "culture", "Recreated 13th-c. Tuscan castle + winery.", { maps: "Castello di Amorosa, 4045 St Helena Hwy, Calistoga CA" }),
    I("napa", "di Rosa Center for Contemporary Art", "museum", "200-acre estate, contemporary art, sculpture park + lake.", { maps: "di Rosa Center for Contemporary Art, 5200 Sonoma Hwy, Napa CA" }),
    I("napa", "Napa Valley Vine Trail run", "run", "Paved, vineyard-lined, runs through Yountville. Go early before the heat.", { maps: "Napa Valley Vine Trail, Yountville CA" }),
    I("napa", "Trefethen Winery", "drink", "Historic estate.", { maps: "Trefethen Family Vineyards, 1160 Oak Knoll Ave, Napa CA" }),
    I("napa", "Truchard Winery", "drink", "Tiny family operation, caves.", { maps: "Truchard Vineyards, 3234 Old Sonoma Rd, Napa CA" }),
    I("napa", "Sequoia Grove Winery", "drink", "Relaxed, under the redwoods.", { maps: "Sequoia Grove Winery, 8338 St Helena Hwy, Rutherford CA" }),
    I("napa", "Bistro Jeanty (Yountville)", "food", "French country classic. Tomato soup en croûte is the signature.", { pinned: true, confirm: true, maps: "Bistro Jeanty, 6510 Washington St, Yountville CA" }),
    I("napa", "The French Laundry", "food", "Book far ahead. The splurge.", { confirm: true, maps: "The French Laundry, 6640 Washington St, Yountville CA" }),
    I("napa", "RH Yountville", "food", "Stunning lunch.", { maps: "RH Yountville, 6725 Washington St, Yountville CA" }),
    I("napa", "Wilfred's Lounge", "bar", "Tiki rooftop on the river.", { maps: "Wilfred's Lounge, Napa CA" }),
    I("napa", "Bistro Don Giovanni", "food", "Beloved local Italian in a vineyard setting (~30 yrs).", { maps: "Bistro Don Giovanni, 4110 Howard Ln, Napa CA" }),

    // ===================== SOUTH BAY / SF =====================
    I("southbay", "SF Giants vs Athletics — day game", "baseball", "Thu 25, 12:45pm at Oracle Park. Oracle → Levi's is doable on Caltrain/drive.", { date: "2026-06-25", time: "12:45", pinned: true, maps: "Oracle Park, 24 Willie Mays Plaza, San Francisco CA" }),
    I("southbay", "Golden State Valkyries (WNBA)", "wnba", "Chase Center, Fri 26 evening. Solo if Andy has a later flight.", { date: "2026-06-26", maps: "Chase Center, 1 Warriors Way, San Francisco CA" }),
    I("southbay", "San Pedro Square Market (San Jose)", "food", "Food hall + bars. ~10 min from hotel.", { maps: "San Pedro Square Market, 87 N San Pedro St, San Jose CA" }),
    I("southbay", "Santana Row — El Jardín", "food", "Mexican, great margaritas.", { maps: "El Jardin, Santana Row, San Jose CA" }),
    I("southbay", "Taplands (Santa Clara)", "drink", "Excellent rotating taproom. Near Levi's.", { maps: "Taplands, Santa Clara CA" }),
    I("southbay", "Ferry Building Marketplace", "market", "Oysters, Dandelion chocolate, local everything.", { maps: "Ferry Building Marketplace, 1 Ferry Building, San Francisco CA" }),
    I("southbay", "Golden Gate Bridge / Crissy Field", "view", "Walk or bike.", { maps: "Golden Gate Bridge, San Francisco CA" }),
    I("southbay", "Alcatraz", "culture", "Book well ahead.", { confirm: true, maps: "Alcatraz Island, San Francisco CA" }),
    I("southbay", "Mission District murals + taquerias", "culture", "Walk Clarion Alley, eat a burrito.", { maps: "Clarion Alley Mural Project, Mission District, San Francisco CA" }),
    I("southbay", "SFMOMA", "museum", "Seven floors of modern art.", { maps: "SFMOMA, 151 3rd St, San Francisco CA" }),
    I("southbay", "de Young Museum", "museum", "Golden Gate Park. Free observation tower.", { maps: "de Young Museum, 50 Hagiwara Tea Garden Dr, San Francisco CA" }),
    I("southbay", "Winchester Mystery House", "culture", "San Jose's gloriously weird mansion. ~10 min from hotel.", { maps: "Winchester Mystery House, 525 S Winchester Blvd, San Jose CA" }),
    I("southbay", "Computer History Museum (Mountain View)", "museum", "Proper Silicon Valley pilgrimage.", { maps: "Computer History Museum, 1401 N Shoreline Blvd, Mountain View CA" }),
    I("southbay", "Embarcadero → Crissy Field run", "run", "Marina Green → toward the Golden Gate Bridge. The definitive SF waterfront run.", { maps: "Embarcadero, San Francisco CA" }),
    I("southbay", "The Morris", "food", "Incredible duck, Chartreuse slushy.", { maps: "The Morris, 2501 Mariposa St, San Francisco CA" }),
    I("southbay", "Hog Island Oysters (Ferry Bldg)", "food", "Counter classic.", { maps: "Hog Island Oyster Co, Ferry Building, San Francisco CA" }),
    I("southbay", "Swan Oyster Depot", "food", "Legendary counter on Polk. Go early.", { maps: "Swan Oyster Depot, 1517 Polk St, San Francisco CA" }),
    I("southbay", "House of Prime Rib", "food", "Van Ness, a clubby classic.", { maps: "House of Prime Rib, 1906 Van Ness Ave, San Francisco CA" }),
    I("southbay", "Bix", "food", "Art-deco jazz supper club near Jackson Square.", { maps: "Bix Restaurant, 56 Gold St, San Francisco CA" }),
    I("southbay", "Mission burrito (SF specialty)", "food", "The city's defining lunch. Try Taquería El Farolito or La Taquería.", { maps: "Taqueria El Farolito, 2779 Mission St, San Francisco CA" }),
  ];

  const DRIVES = [
    { from: "vancouver", to: "seattle1", mode: "bus", duration_h: 3.5, distance_km: 230, note: "Cross-border by bus. Have passports ready." },
    { from: "seattle1", to: "olympic", mode: "drive", duration_h: 2.5, distance_km: 135, note: "Pick up rental car. Ferry option via Bainbridge/Edmonds." },
    { from: "olympic", to: "seattle2", mode: "drive", duration_h: 2.5, distance_km: 135, note: "Drop straight to the SeaTac hotel." },
    { from: "seattle2", to: "portland", mode: "drive", duration_h: 5.0, distance_km: 280, note: "I-5 south. Plan a lunch stop." },
    { from: "portland", to: "craterlake", mode: "drive", duration_h: 4.5, distance_km: 380, note: "South via I-5 then east. Sparse services near the park — fuel up." },
    { from: "craterlake", to: "napa", mode: "drive", duration_h: 8.5, distance_km: 700, note: "The big one: 7–10 hr. Patchy signal — download offline maps." },
    { from: "napa", to: "southbay", mode: "drive", duration_h: 1.5, distance_km: 110, note: "Through SF or via 680. Traffic-dependent." },
  ];

  const CONFIRMATIONS = [
    { id: "c-canadians", text: "Vancouver Canadians game (Fri 12 eve)", where: "milb.com/vancouver" },
    { id: "c-storm", text: "Seattle Storm home game on 14th/15th?", where: "climatepledgearena.com" },
    { id: "c-rainiers-14", text: "Tacoma Rainiers Sun 14, 1:35pm", where: "milb.com/tacoma" },
    { id: "c-canlis", text: "Canlis dinner reservation", where: "canlis.com" },
    { id: "c-aquasox", text: "Everett AquaSox home on 18th?", where: "milb.com/everett" },
    { id: "c-portland-fire", text: "Portland Fire WNBA home Sat 20?", where: "fire.wnba.com/schedule" },
    { id: "c-hops", text: "Hillsboro Hops home Sat 20?", where: "milb.com/hillsboro" },
    { id: "c-rivercats", text: "Sacramento River Cats Tue 23", where: "milb.com/sacramento" },
    { id: "c-crater-dining", text: "Crater Lake Lodge dining reservation", where: "craterlakelodges.com" },
    { id: "c-jeanty", text: "Bistro Jeanty (Yountville)", where: "bistrojeanty.com" },
    { id: "c-french-laundry", text: "The French Laundry (long lead)", where: "tfl.com" },
    { id: "c-napa-tastings", text: "Napa winery tastings (Trefethen / Truchard / Sequoia Grove)", where: "winery sites" },
    { id: "c-alcatraz", text: "Alcatraz tour booking", where: "alcatrazcruises.com" },
    { id: "c-skytrain", text: "Vancouver match-day: use Main Street–Science World (Stadium–Chinatown closed)", where: "translink.ca" },
  ];

  const DAYS = [
    { date: "2026-06-12", stop: "vancouver", title: "Land in Vancouver", note: "Arrive. Settle in Yaletown. Easy first night." },
    { date: "2026-06-13", stop: "vancouver", title: "Match Day · Australia v Türkiye", note: "Day in town, big match at 9pm." },
    { date: "2026-06-14", stop: "seattle1", title: "Vancouver → Seattle", note: "Cross-border by bus. Land at Seattle Center hotel." },
    { date: "2026-06-15", stop: "seattle1", title: "Fan-zone Day", note: "Belgium v Egypt 12pm. Fan festival next to hotel." },
    { date: "2026-06-16", stop: "olympic", title: "Seattle → Olympic", note: "Pick up rental. ~2.5 hr drive. Lefties game tonight?" },
    { date: "2026-06-17", stop: "olympic", title: "Big park day", note: "Hurricane Ridge morning + Hoh Rainforest, or split." },
    { date: "2026-06-18", stop: "seattle2", title: "Olympic → SeaTac · Mariners day", note: "Back through Seattle. Mariners 1:10pm at T-Mobile." },
    { date: "2026-06-19", stop: "seattle2", title: "Match Day · USA v Australia", note: "12pm at Lumen. Mariners 7:10pm bonus stack." },
    { date: "2026-06-20", stop: "portland", title: "Seattle → Portland", note: "5 hr drive. Pickles or Fire in the evening." },
    { date: "2026-06-21", stop: "craterlake", title: "Portland → Crater Lake", note: "4.5 hr drive. Sunset terrace drink." },
    { date: "2026-06-22", stop: "craterlake", title: "Crater Lake hiking day", note: "Rim Drive + Watchman / Garfield. Altitude — pace it." },
    { date: "2026-06-23", stop: "napa", title: "Crater Lake → Napa", note: "Long drive (7–10 hr). River Cats tonight if not wrecked." },
    { date: "2026-06-24", stop: "napa", title: "Wine country day", note: "Balloon at sunrise. Tastings. Bistro Jeanty for dinner." },
    { date: "2026-06-25", stop: "southbay", title: "Match Day · Paraguay v Australia", note: "Napa → San Jose. Levi's 7pm. The finale." },
    { date: "2026-06-26", stop: "southbay", title: "Last day · SF", note: "Will flies 10pm. SF city day or Silicon Valley pilgrimage." },
  ];

  window.TRIP_DATA = { STOPS, MATCHES, IDEAS, DRIVES, CONFIRMATIONS, DAYS };
})();
